### ISSUE TITLE
MQTT channel

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/forum#10]
I am looking for the MQTT channel. Where is it and are there some examples on usage?

Knut Eilif

**Comment by brice-morin** [comment]
@kehusa please assigne @maxleiko to the Kevoree-related issues and @brice-morin for the ThingML-related issues, so that we get an explicit notification and do not need to watch our home page at github.com all day long ;-)

**Comment by maxleiko** [comment]
[Java MQTTChannel](https://github.com/kevoree/kevoree-library/tree/master/java/org.kevoree.library.java.mqtt#MQTTChannel) location  

[Javascript MQTTChannel](https://github.com/kevoree/kevoree-js/tree/master/library/kevoree-chan-mqtt) location  

You can find usage examples in the different **kevscript** files. But I've made a cross-platform test earlier this week (between MQTT JS <-> MQTT Java) and the channels aren't interoperable for now.  

I'll work on a fix asap

**Comment by maxleiko** [comment]
@brice-morin you are not forced to be assigned to get notifications, you can just tweak your notification settings in your [GitHub Profile](https://github.com/settings/notifications)

**Comment by kehusa** [comment]
Looking for examples of MQTT Channel usage. The link to Javascript MQTTChannel location in previous post seems to be broken.

**Comment by maxleiko** [comment]
I've restructured the `kevoree-js` repository, and I did not yet re-create a repo just for the MQTT Channel (putting this on my todo list)
But for now, you can browse th repo history to find the sources/kevs [here](https://github.com/kevoree/kevoree-js/tree/cd17c3eb732b949d03df84d5359d1670e1167318/library/kevoree-chan-mqtt)

**Comment by maxleiko** [comment]
@kehusa keep in mind that this is a 7 month old version. So there is a lot to change in the KevScript, like the WebSocketGroup is now WSGroup, and the components used for toying are Ticker and ConsolePrinter (no more FakeConsole, etc)

**Comment by maxleiko** [comment]
@kehusa I've created the brand new repo for the Javascript MQTTChannel [here](https://github.com/kevoree/kevoree-js-chan-mqtt)

I did not publish it to the npm registry yet. I need to update the Java version accordingly :)

**Comment by kehusa** [comment]
Thx, Should I wait trying MQTT chan until you have published to npm?

**Comment by maxleiko** [comment]
@kehusa ok, I've just released the new MQTTChannel/5.2.9-SNAPSHOT for Js & Java

> Note that this is only -SNAPSHOT (so you have to specify the version explicitly in your KevScripts)

**Comment by kehusa** [comment]
ok, got it :-)
