### ISSUE TITLE
What is the path structure in MQTT publish topic

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/forum#12]
in the MQTT channel: https://github.com/kevoree/kevoree-js-chan-mqtt, line 118:  this.client.publish(this.uuid+path, msg+'');, a path is appended to the uuid forming the topic. What is the path structure like? And remember that I am sending messages on thingml ports. It is important to know for subscribers to messages coming from the kevoree mqtt channel.

**Comment by maxleiko** [comment]
It's the Kevoree path of the destination port, so, in this example:

```
add myNode: JavascriptNode
add myNode.printer: ConsolePrinter
```

The `path` section would be `nodes[myNode]/components[printer]/provided[input]`
