### ISSUE TITLE
Latest and greatest kevoree

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/forum#13]
I am trying to run an eclipse generated project with the onDisconnect feature, but then I get:

What do I need to change to get the last version of kevoree??

C:\Users\KnutEilif\Heads_13.02\workspace\Training\thingml-gen\javascript\HomeGW\
kevs>kevoreejs -p . -n node0 --kevscript main.kevs
09:58:18  ALL    KevoreeLogger    Set logLevel= info
09:58:18  INFO   KevoreeCore      Platform node name: node0
09:58:20  ERROR  NodeJSRuntime    Unable to load Kevoree KevScript: Unknown attr
ibute "onDisconnect" in /groups[sync](set sync.onDisconnect =)
09:58:20  ERROR  NodeJSRuntime    Platform shut down.

C:\Users\KnutEilif\AppData\Roaming\npm\node_modules\kevoree-nodejs-runtime\node_
modules\kevoree-commons\lib\Bootstrapper.js:39
            var meta = node.typeDefinition.select('deployUnits[name=*]/filters
                                           ^
TypeError: Cannot call method 'select' of null
    at PseudoClass.Class.bootstrapNodeType (C:\Users\KnutEilif\AppData\Roaming\n
pm\node_modules\kevoree-nodejs-runtime\node_modules\kevoree-commons\lib\Bootstra
pper.js:39:44)
    at PseudoClass.Class.checkBootstrapNode (C:\Users\KnutEilif\AppData\Roaming\
npm\node_modules\kevoree-nodejs-runtime\node_modules\kevoree-core\kevoree-core.j
s:319:31)
    at PseudoClass.Class.deploy (C:\Users\KnutEilif\AppData\Roaming\npm\node_mod
ules\kevoree-nodejs-runtime\node_modules\kevoree-core\kevoree-core.js:124:22)
    at PseudoClass.Class.stop (C:\Users\KnutEilif\AppData\Roaming\npm\node_modul
es\kevoree-nodejs-runtime\node_modules\kevoree-core\kevoree-core.js:307:18)
    at PseudoClass.Class.stop (C:\Users\KnutEilif\AppData\Roaming\npm\node_modul
es\kevoree-nodejs-runtime\lib\NodeJSRuntime.js:128:20)
    at errorHandler (C:\Users\KnutEilif\AppData\Roaming\npm\node_modules\kevoree
-nodejs-runtime\cli.js:78:17)
    at C:\Users\KnutEilif\AppData\Roaming\npm\node_modules\kevoree-nodejs-runtim
e\cli.js:99:29
    at C:\Users\KnutEilif\AppData\Roaming\npm\node_modules\kevoree-nodejs-runtim
e\node_modules\kevoree-kevscript\lib\interpreter.js:84:9
    at C:\Users\KnutEilif\AppData\Roaming\npm\node_modules\kevoree-nodejs-runtim
e\node_modules\kevoree-kevscript\node_modules\async\lib\async.js:254:17
    at C:\Users\KnutEilif\AppData\Roaming\npm\node_modules\kevoree-nodejs-runtim
e\node_modules\kevoree-kevscript\node_modules\async\lib\async.js:151:21

C:\Users\KnutEilif\Heads_13.02\workspace\Training\thingml-gen\javascript\HomeGW\
kevs>

**Comment by maxleiko** [comment]
If you have a doubt on how outdated your current version is, you can remove both `.deploy_units/` and `node_modules/` and then run `npm install` and after `grunt kevoree`

**Comment by kehusa** [comment]
Hmm, I deleted node_modules. Didn't have any deploy units and got:
kevs>npm install
|

> HomeGW@1.0.0 prepublish C:\Users\KnutEilif\Heads_13.02\workspace\Training\thin
> gml-gen\javascript\HomeGW
> grunt

Running "kevoree_genmodel:main" (kevoree_genmodel) task
Package:         my.package
TypeDefinition:  HomeGW
Version:         1.0.0
DeployUnit:      HomeGW
Input port(s):   [ HomeGW_server_sensor_service_in ]
Output port(s):  [ HomeGW_server_sensor_service_out, HomeGW_server_smarttracker_
out ]

Model generation done
Model 'kevlib.json' saved at kevlib.json

Done, without errors.
state.js@4.1.8 ..\node_modules\state.js

grunt@0.4.5 ..\node_modules\grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.5)
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.6.1)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
└── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)

grunt-kevoree-registry@2.0.2 ..\node_modules\grunt-kevoree-registry
├── kevoree-registry-client@2.2.2 (minimist@1.1.1, chalk@0.5.1)
└── kevoree-library@5.0.8 (kevoree-kotlin@1.0.3)

kevoree-entities@8.0.4 ..\node_modules\kevoree-entities
├── pseudoclass@1.0.3
├── kevoree-commons@2.1.2 (chalk@0.4.0)
├── kevoree-kevscript@2.2.3 (waxeye@0.8.1, async@0.9.0, kevoree-kotlin@1.0.3, se
mver@4.3.3, chalk@0.5.1, optimist@0.6.1, kevoree-registry-client@2.2.2)
└── kevoree-library@5.0.8 (kevoree-kotlin@1.0.3)

grunt-kevoree@5.4.2 ..\node_modules\grunt-kevoree
├── async@0.9.0
├── kevoree-commons@2.1.2 (chalk@0.4.0, pseudoclass@1.0.3)
├── npmi@1.0.1 (semver@4.3.3)
├── kevoree-resolvers@2.2.0 (npm-vers@0.1.1)
├── serve-static@1.9.2 (utils-merge@1.0.0, escape-html@1.0.1, parseurl@1.3.0, se
nd@0.12.2)
├── express@4.12.3 (merge-descriptors@1.0.0, utils-merge@1.0.0, cookie-signature
@1.0.6, methods@1.1.1, cookie@0.1.2, escape-html@1.0.1, fresh@0.2.4, range-parse
r@1.0.2, content-type@1.0.1, finalhandler@0.3.4, vary@1.0.0, parseurl@1.3.0, con
tent-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.1, on-finished@2.2.1, qs@
2.4.1, debug@2.1.3, etag@1.5.1, send@0.12.2, proxy-addr@1.0.7, accepts@1.2.5, ty
pe-is@1.6.1)
├── kevoree-kevscript@2.2.3 (waxeye@0.8.1, pseudoclass@1.0.3, chalk@0.5.1, semve
r@4.3.3, kevoree-kotlin@1.0.3, optimist@0.6.1, kevoree-registry-client@2.2.2)
├── kevoree-library@5.0.8 (kevoree-kotlin@1.0.3)
└── npm@2.8.4

grunt-kevoree-genmodel@2.0.0 ..\node_modules\grunt-kevoree-genmodel
└── kevoree-gen-model@2.0.8 (kevoree-kotlin@1.0.3, chalk@0.5.1, optimist@0.6.1,
kevoree-entities@6.0.0, kevoree-library@5.0.8, npm@2.8.4)

C:\Users\KnutEilif\Heads_13.02\workspace\Training\thingml-gen\javascript\HomeGW\
kevs>cd ..

C:\Users\KnutEilif\Heads_13.02\workspace\Training\thingml-gen\javascript\HomeGW>
grunt kevoree --node=node0
Running "kevoree" task
11:37:29  ALL    KevoreeLogger    Set logLevel= debug

> > Platform node name: node0
> > Bootstrap script: kevs\main.kevs
> > 11:37:29  DEBUG  NPMResolver      modulesPath= C:\Users\KnutEilif\Heads_13.02\wo
> > rkspace\Training\thingml-gen\javascript\HomeGW.deploy_units\node0
> > Fatal error: "grunt-kevoree" unable to parse KevScript
> > Unknown attribute "onDisconnect" in /groups[sync](set sync.onDisconnect =)

C:\Users\KnutEilif\Heads_13.02\workspace\Training\thingml-gen\javascript\HomeGW>

**Comment by maxleiko** [comment]
Did you specify `5.2.9-SNAPSHOT` for your `WSGroup` version ?

**Comment by maxleiko** [comment]
I did **not** release 5.2.9 yet, so `onDisconnect` is only available in the snapshot version

**Comment by kehusa** [comment]
That was it:-) Thanks a lot.
