### ISSUE TITLE
Extension of MQTT component

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/forum#18]
@brice-morin @maxleiko I wonder if it would be an idea to extend the functionality of the MQTT pub and sub clients by handing the topic. Currently the topic that you receive the message on is just thrown away. This is important info as you might subscribe for a topic containing wildcards. Would it then be an idea to add another port emitting the messages on a json format like {"topic" : "someTopic", "value" : "someValue"}? The same could also be the case for the publisher components. It could have a port that accepts a message on the format {"topic" : "someTopic", "value" : "someValue"}.
One alternative to this  is to have separate pub and sub components for every topic you want to publish and subscribe to/from. This doesn't scale and is not dynamic. Or one could use the mqtt libraries directly from within the thingml code.
What do you think is the right direction to follow?

**Comment by maxleiko** [comment]
MQTT Pub & Sub components already handle **topics**.  
What do you mean by "thrown away" ?

**Comment by maxleiko** [comment]
Ooh, I think I see what you mean.  
You want to use wildcards in your topic path, but then, when you receive a message you also want to know which topic sent it, is that it ?

**Comment by kehusa** [comment]
Yes, the topic is not sent along with the message:

 // register "message" event listener
            this.client.on('message', function (topic, msg) {
                this.out_onMsg(msg);
            }.bind(this));

**Comment by maxleiko** [comment]
The idea you gave with the double port is the easiest to implement :)

**Comment by maxleiko** [comment]
Check out `MQTTSubClient/2.0.0` [here](https://github.com/kevoree/kevoree-js-comp-mqttsubclient/tree/v2.0.0)

**Comment by kehusa** [comment]
Thanks a lot :-) Can you do the same thing for the publish component, make
a port that accepts topic and msg and that publishes to this topic instead
of the default.

2015-05-20 12:40 GMT+02:00 Maxime Tricoire notifications@github.com:

> Check out MQTTSubClient/2.0.0 here
> https://github.com/kevoree/kevoree-js-comp-mqttsubclient/tree/v2.0.0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HEADS-project/forum/issues/18#issuecomment-103839561.

## 

| Knut Eilif Husa | CTO | Tellu AS | Hagaløkkveien 13, 1383 Asker - NORWAY|
Direct: +47 452 49496 | www.tellu.no |

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system.

**Comment by maxleiko** [comment]
Check out `MQTTPubClient/2.0.0` [here](https://github.com/kevoree/kevoree-js-comp-mqttpubclient/tree/v2.0.0)
